### ISSUE TITLE
Running install_scripts (installing ya* script to /usr/local/bin) does not work

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#15]
On Py3.9.2 this creates all the necessary ya* scripts:

`python setup.py install`

but this does not create all the necessary ya* scripts:

`pip install git+https://github.com/tilde-lab/yascheduler`

**Comment by blokhin** [comment]
`pip 20.3.4`

**Comment by blokhin** [comment]
@knopki do you think the simple command `yascheduler` should work? Does it make sense?

**Comment by knopki** [comment]
@knopki Yes, why not? This is more convenient than `python3 -m yascheduler.scheduler`. I move `daemonize()` to `utils.py` and add `"yascheduler = yascheduler.utils:daemonize"` to `setup.json`.
