### ISSUE TITLE
Suspicious assignment

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#33]
https://github.com/tilde-lab/yascheduler/blob/64fd89afd525e758b80f8aeb9c5e46111e63a3e1/yascheduler/scheduler.py#L339-L340

@knopki why is this needed?

**Comment by knopki** [comment]
Task's metadata overwritten when task becomes done. But webhook URL is required later, therefore it resaved to the new metadata.
In fact, this whole block doesn't look too pretty.

**Comment by blokhin** [comment]
Ah, yes, I see! Thank you.
