### ISSUE TITLE
Per-engine sleep_interval

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#34]
e.g. for some engine 6 seconds might be fine, but for the other might be too much...

**Comment by Ninja-mann** [comment]
> e.g. for some engines 6 seconds might be fine, but for the others
e```
function test() {
  console.log("notice the blank line before this function?");
}
``` might be too much...

#28 

- [ ] https://github.com/Utreon

**Comment by knopki** [comment]
Implemented in #49
