### ISSUE TITLE
Out of sync between yascheduler and AiiDA

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#4]
The commands
`verdi process list -P pk label job_state scheduler_state -O id | grep run`
and
`psql -d yascheduler -c 'select task_id, label, ip from yascheduler_tasks where status=1 order by 2;'`

quite unexpectedly, may produce slightly different output in terms of the running tasks. Might be related to https://groups.google.com/forum/#!topic/aiidausers/zJiD-3eZeoM

**Comment by blokhin** [comment]
In other words, the output of:
`verdi process list | grep RUNNING | wc -l`
!=
`yastatus | grep RUNNING | wc -l`

**Comment by ansobolev** [comment]
Some steps to replicate? When exactly does it happen? This may happen, if verdi daemon has not retrieved results of the just finished process.

**Comment by blokhin** [comment]
>This may happen, if verdi daemon has not retrieved results of the just finished process.

No, it persists.

>Some steps to replicate? When exactly does it happen?

Hard to say. I did nothing special, except the AiiDA daemon restart.

**Comment by blokhin** [comment]
Closed in favor of #8
