### ISSUE TITLE
Daemon exits on Enter press

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#5]
(may be this is not a bug, but feature?)
Pressing ENTER leads to:
```
"/lib/python3.6/site-packages/invoke/terminals.py", line 231, in bytes_to_read
    fionread = fcntl.ioctl(input_, termios.FIONREAD, "  ")
AttributeError: module 'termios' has no attribute 'FIONREAD'
```

**Comment by ansobolev** [comment]
Any definite steps to reproduce?

**Comment by blokhin** [comment]
1. Run daemon in foreground
2. Hit Enter

**Comment by ansobolev** [comment]
Why do you want to run it in the foreground? It is meant to be run with systemd

**Comment by blokhin** [comment]
This is actual for the standalone usage, without AiiDA, e.g. to test some nasty systems

**Comment by ansobolev** [comment]
OK, I'll take a look into it

**Comment by ansobolev** [comment]
Unfortunately, I cannot reproduce the bug. From the error message it seems like a bug in Python standard lib (`invoke` module). Closing as `WORKSFORME`.
